# Generated by Django 5.0.2 on 2024-04-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0007_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
