# Generated by Django 5.0.2 on 2024-04-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0008_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
