# Generated by Django 5.0.2 on 2024-04-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1', '0013_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
